WindowsFormsApp1/NeteaseMusicAPI.cs

更新网易云音乐URL

---

WindowsFormsApp1/MainForm.cs
WindowsFormsApp1/NetEaseMusicVO.cs

- 修复 v3.3 版本中，对于单个歌曲，保存时直接报错的问题
- 优化输入多个 ID 时，对空格的处理
- 优化获取 VIP 歌曲直链时的错误提示
- 优化批量处理时，控制台日志

Release v3.4

---

WindowsFormsApp1/INeteaseMusicApi.cs
WindowsFormsApp1/MainForm.Designer.cs
WindowsFormsApp1/MainForm.cs
WindowsFormsApp1/NetEaseMusicApi.cs
WindowsFormsApp1/NetEaseMusicApiWrapper.cs
WindowsFormsApp1/NetEaseMusicCache.cs
WindowsFormsApp1/NetEaseMusicUtils.cs
WindowsFormsApp1/NetEaseMusicVO.cs

（1）New Feature
- 输出区域支持复制
- 保存时新增 `Unicode` 编码格式
（2）Fix Bugs
- 修复点击保存按钮前如果配置发生变更时，需要重新点击搜索按钮才能保存的问题
（3）Optimized
- 提升批量搜索时的程序性能

Release v3.5

---

WindowsFormsApp1/MainForm.Designer.cs
WindowsFormsApp1/MainForm.cs
WindowsFormsApp1/NetEaseMusicUtils.cs
WindowsFormsApp1/NetEaseMusicVO.cs

（1）New Feature
- 支持 srt 格式输出 #23 
（2）Fix Bugs
- 修复点击搜索不存在的歌曲时，程序报错问题

Release v3.6

---

WindowsFormsApp1/MainForm.cs
WindowsFormsApp1/NetEaseMusicUtils.cs
WindowsFormsApp1/NetEaseMusicVO.cs

Release v3.7

---

WindowsFormsApp1/MainForm.cs
WindowsFormsApp1/NetEaseMusicUtils.cs
WindowsFormsApp1/NetEaseMusicVO.cs

support input url and extract id automatic

---

MusicLyricApp/Bean/SettingBean.cs
MusicLyricApp/MainForm.Designer.cs
MusicLyricApp/MainForm.cs
MusicLyricApp/MainForm.resx
MusicLyricApp/MusicLyricApp.csproj
MusicLyricApp/Program.cs
MusicLyricApp/SettingForm.Designer.cs
MusicLyricApp/SettingForm.cs
MusicLyricApp/SettingForm.resx
MusicLyricApp/Utils/Constants.cs

（1）New Feature
- 为了解决配置项越来越多问题，新增了更多设置的窗口
- 支持记住最后配置功能 #76 
- 支持自动读取剪贴板内容功能 #60 
- 支持自动检查更新 #59 
（2）Optimized
- 规范化组件名称

add setting panel && optimizedcomponent name

---

MusicLyricApp/App.config
MusicLyricApp/MainForm.cs

- 修复文字显示模糊问题
- 高DPI下将字体设置为Segoe UI

尝试优化高DPI下显示质量

---

MusicLyricApp/Api/QQMusicApiV2.cs
MusicLyricApp/Bean/Constants.cs
MusicLyricApp/Bean/MusicLyricsVO.cs
MusicLyricApp/Bean/QQMusicBean.cs
MusicLyricApp/Utils/GlobalUtils.cs
MusicLyricApp/Utils/LyricUtils.cs
MusicLyricApp/Utils/RomajiUtils.cs
MusicLyricApp/Utils/SrtUtils.cs
MusicLyricAppTest/Bean/MusicLyricsVOTest.cs
MusicLyricAppTest/MusicLyricAppTest.csproj
MusicLyricAppTest/Utils/GlobalUtilsTest.cs
MusicLyricAppTest/Utils/LyricUtilsTest.cs
MusicLyricAppTest/Utils/SrtUtilsTest.cs

（1）Fix Bugs
- 修复独立模式导出 SRT 歌词时，时间轴连接部分错误问题 #86 
- 修复 v4.2 版本强制两位功能失效的问题 #88 
（2）Optimized
- 优化 QQ 音乐导出 SRT 歌词时，存在 `//` 的问题 #85

Release v4.3

---

MusicLyricApp/Bean/Constants.cs
MusicLyricApp/MainForm.cs
MusicLyricApp/Utils/SrtUtils.cs
MusicLyricAppTest/Utils/LyricUtilsTest.cs
MusicLyricAppTest/Utils/SrtUtilsTest.cs

（1）Fix Bugs
- 修复 SRT 歌词丢失最后一行的问题 #95
（）New Feature
- 输入框支持输入本地文件夹路径，读取全部子文件名作为输入 #27 #93 
（3）Optimized
- Bump System.Net.Http from 4.3.0 to 4.3.4 #91
- Bump System.Text.RegularExpressions from 4.3.0 to 4.3.1 #92

Release v4.4

---

MusicLyricApp/Bean/Constants.cs
MusicLyricApp/Bean/MusicLyricsVO.cs
MusicLyricApp/Bean/SettingBase.cs
MusicLyricApp/SettingForm.Designer.cs
MusicLyricApp/SettingForm.cs
MusicLyricApp/Utils/LyricUtils.cs

（1）New Feature
-译文歌词缺省时支持多种处理逻辑 #106

Release v4.6

---

MusicLyricApp/Bean/Constants.cs
MusicLyricApp/Bean/MusicLyricsVO.cs
MusicLyricApp/Utils/LyricUtils.cs
MusicLyricAppTest/Bean/LyricTimestampTest.cs
MusicLyricAppTest/Bean/MusicLyricsVOTest.cs

（1）Fix Bugs
- 修复译文缺省功能在部分歌词输出格式中错误的问题 #108 
- 修复歌词时间戳位数截取时的策略错误问题 #109

Release v4.7

---

MusicLyricApp/Bean/Constants.cs
MusicLyricApp/Bean/MusicLyricsVO.cs
MusicLyricAppTest/Bean/MusicLyricsVOTest.cs

（1）Fix Bugs
- 修复部分译文歌词搜索时数组越界的报错 #112

Release v4.8

---

MusicLyricApp/Api/IMusicApiV2.cs
MusicLyricApp/Api/MusicApiV2Cacheable.cs
MusicLyricApp/Api/NetEaseMusicApiV2.cs
MusicLyricApp/Api/QQMusicApiV2.cs
MusicLyricApp/Bean/Constants.cs
MusicLyricApp/Bean/MusicLyricsVO.cs
MusicLyricApp/Bean/QQMusicBean.cs
MusicLyricApp/MainForm.cs

（1）Fix Bugs
- 修复 QQ 音乐歌词不存在时可能报错的问题 #127

Release v5.0

---

README.md

Hi there, I was just reading your bilingual documentation in README.md today and figured it could use some improvements, I retranslated several parts to English so that they are grammatically correct and hopefully sound more natural too (I did try to find a **balance between being accurate and sounding natural**).
I also improved the punctuations and spaces in a few spots following [this guideline](https://github.com/sparanoid/chinese-copywriting-guidelines) for Chinese-English bilingual content.
Kindly let me know if it looks all good to you, I can also explain if you ever wonder about why I made a certain change in my commit.
Oh, and one last thing, **keep up the great work**! 👍

Made improvements to the bilingual content in the documentation

---

MusicLyricApp/Api/Music/NetEaseMusicNativeApi.cs
MusicLyricApp/Bean/Constants.cs
MusicLyricApp/Bean/CsvBean.cs
MusicLyricApp/MainForm.Designer.cs
MusicLyricApp/MainForm.cs
MusicLyricApp/Utils/GlobalUtils.cs
MusicLyricApp/Utils/HttpUtils.cs
MusicLyricApp/Utils/LyricUtils.cs

（1）Fix Bugs
- 修复搜索专辑时，无法下载封面图片的问题
- 修复使用交错模式导出歌词时，由于歌词数量不足导致的保存失败问题 #170
（2）Optimized
- 优化读取剪贴板功能，更加智能，降低误触率 #165 
- 歌曲直链进行批量保存时，导出文件名保持和导出歌词文件名的规则一致 #168

Release v6.0

---

MusicLyricApp/MainForm.cs
MusicLyricApp/Utils/GlobalUtils.cs
MusicLyricApp/Utils/HttpUtils.cs

（1）Fix Bugs
- 修复批量保存歌曲直链时，可能出现的程序崩溃问题

Supplement For Release v6.0

---

MusicLyricApp/Api/Music/NetEaseMusicApi.cs
MusicLyricApp/Api/Music/NetEaseMusicNativeApi.cs
MusicLyricApp/Bean/Constants.cs
MusicLyricApp/Bean/MusicLyricsVO.cs
MusicLyricApp/Utils/RomajiUtils.cs
MusicLyricAppTest/Api/Music/NetEaseMusicNativeApi.cs

（1）Fix Bugs
- 修复保存时潜在的内存泄漏问题 #187 
（2）Optimized
- 修改网易云模糊搜索接口，需要提供鉴权信息 #186

Release v6.1

---

MusicLyricApp/Api/Music/QQMusicApi.cs
MusicLyricApp/Bean/Constants.cs
MusicLyricApp/MainForm.cs
MusicLyricApp/Utils/GlobalUtils.cs
README.md

（1）Fix Bugs
- 修复 QQ 音乐获取歌名可能不正确的问题 #212 
- 修复扫盘功能可能报错 “您输入的 ID 不合法” 问题 #213 
- 修复 QQ 音乐逐字歌词和 “原始译文” 的兼容性问题 #214

Release v6.3

---

MusicLyricApp/Api/Music/BaseNativeApi.cs
MusicLyricApp/Bean/Constants.cs
MusicLyricApp/Bean/MusicLyricsVO.cs
MusicLyricAppTest/Api/Music/NetEaseMusicNativeApi.cs
README.md

（1）Fix Bugs
- 解决网易云 API 更新后匿名状态无法使用功能的问题 #229

Release v6.4
